export * from "./types.js";
export { reportBaseCss } from "./styles/index.js";
export { buildEmbeddedFontFaceCss, buildLocalFontFaceCss, reportFontFaces } from "./fonts/index.js";
export type { ReportFontFace } from "./fonts/index.js";

export { ResearchReport } from "./components/ResearchReport.js";
export type { ResearchReportProps } from "./components/ResearchReport.js";
export { Hero } from "./components/Hero.js";
export type { HeroProps } from "./components/Hero.js";
export { MetaBlock, MetaColumn, ActorList } from "./components/MetaBlock.js";
export type { MetaBlockProps, MetaColumnProps, ActorListProps } from "./components/MetaBlock.js";
export { TableOfContents } from "./components/TableOfContents.js";
export type { TableOfContentsProps } from "./components/TableOfContents.js";
export { Section } from "./components/Section.js";
export type { SectionProps } from "./components/Section.js";
export { Figure } from "./components/Figure.js";
export type { FigureProps, FigureKind } from "./components/Figure.js";
export { ProgressChart, pickImprovementDirection } from "./components/ProgressChart.js";
export type { ProgressChartProps } from "./components/ProgressChart.js";
export { SmallMultiples } from "./components/SmallMultiples.js";
export type { SmallMultiplesProps } from "./components/SmallMultiples.js";
export { LineageTree } from "./components/LineageTree.js";
export type { LineageTreeProps } from "./components/LineageTree.js";
export { Swimlanes } from "./components/Swimlanes.js";
export type { SwimlanesProps } from "./components/Swimlanes.js";
export { OutcomesTable } from "./components/OutcomesTable.js";
export type { OutcomesTableProps } from "./components/OutcomesTable.js";
export { MetricCard } from "./components/MetricCard.js";
export type { MetricCardProps } from "./components/MetricCard.js";
export { EvidenceBlock, AttachmentList } from "./components/EvidenceBlock.js";
export type { EvidenceBlockProps, AttachmentListProps } from "./components/EvidenceBlock.js";
export { BaselineCard } from "./components/BaselineCard.js";
export type { BaselineCardProps } from "./components/BaselineCard.js";
export { Callout } from "./components/Callout.js";
export type { CalloutKind, CalloutProps } from "./components/Callout.js";
export { Definition } from "./components/Definition.js";
export type { DefinitionProps } from "./components/Definition.js";
export { ReportAside } from "./components/Aside.js";
export type { AsideProps } from "./components/Aside.js";
export { Colophon } from "./components/Colophon.js";
export type { ColophonProps } from "./components/Colophon.js";

export { renderReportToHtml, renderReportToHtmlAsync } from "./render.js";
export type { RenderReportInput, RenderReportResult } from "./render.js";
