import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  shell: {
    display: "grid",
    gridTemplateColumns: {
      default: "216px minmax(0, 1fr)",
      "@media (max-width: 760px)": "minmax(0, 1fr)",
    },
    minHeight: "100vh",
  },
  sidebar: {
    padding: "28px 18px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: "#e5e7eb",
    backgroundColor: "#f8f9fb",
    display: "flex",
    flexDirection: "column",
    gap: 28,
    position: "sticky",
    top: 0,
    height: "100vh",
    boxSizing: "border-box",
    "@media (max-width: 760px)": {
      height: "auto",
      position: "static",
      padding: 16,
      gap: 12,
      borderBottomWidth: 1,
      borderBottomStyle: "solid",
      borderBottomColor: "#e5e7eb",
    },
  },
  brand: {
    fontSize: 21,
    fontWeight: 650,
    letterSpacing: "-0.8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    color: "#18202b",
    textDecoration: "none",
  },
  brandIcon: {
    width: 25,
    height: 25,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "#526de8",
    borderRadius: 7,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 15,
    color: "#526de8",
  },
  nav: { display: "flex", flexDirection: "column", gap: 5 },
  navLink: {
    display: "block",
    color: "#515966",
    padding: "9px 10px",
    borderRadius: 6,
    textDecoration: "none",
    fontSize: 13,
    backgroundColor: { default: "transparent", ":hover": "#edf0f6" },
  },
  selected: { color: "#3049b8", backgroundColor: "#e9edfc" },
  footer: {
    marginTop: "auto",
    color: "#687385",
    fontSize: 12,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  content: {
    minWidth: 0,
    width: "100%",
    maxWidth: 1280,
    padding: {
      default: "34px 44px 60px",
      "@media (max-width: 760px)": "24px 16px",
    },
    boxSizing: "border-box",
    marginInline: "auto",
  },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    alignItems: "flex-start",
    marginBottom: 28,
  },
  title: {
    fontSize: 26,
    fontWeight: 600,
    letterSpacing: "-0.8px",
    margin: "6px 0 8px",
  },
  muted: { color: "#677183", fontSize: 13 },
  eyebrow: {
    fontSize: 11,
    fontWeight: 550,
    letterSpacing: "1px",
    textTransform: "uppercase",
    color: "#707a8a",
  },
  row: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  button: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#dce0e8",
    borderRadius: 6,
    backgroundColor: { default: "white", ":hover": "#f4f6fa" },
    color: "#283349",
    fontSize: 13,
    fontWeight: 500,
    padding: "8px 12px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  primary: {
    backgroundColor: { default: "#5266cf", ":hover": "#4357bd" },
    color: "white",
    borderColor: "#5266cf",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1.65fr) minmax(260px, 1fr)",
      "@media (max-width: 1080px)": "minmax(0, 1fr)",
    },
    gap: 20,
    marginBottom: 24,
  },
  card: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#e2e6ed",
    borderRadius: 9,
    backgroundColor: "#fff",
    minWidth: 0,
    overflow: "hidden",
  },
  cardHead: {
    flexWrap: "wrap",
    padding: "16px 20px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "#eef0f4",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  cardTitle: { fontSize: 13, fontWeight: 600, margin: 0 },
  cardBody: { padding: 20 },
  stats: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, 1fr)",
      "@media (max-width: 760px)": "repeat(2, 1fr)",
    },
    gap: 12,
    marginBottom: 24,
  },
  stat: {
    padding: "16px 18px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#e2e6ed",
    borderRadius: 8,
    backgroundColor: "#fff",
  },
  statValue: { fontSize: 24, letterSpacing: "-0.8px", marginTop: 8 },
  toolbar: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    padding: "12px 16px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "#eef0f4",
  },
  input: {
    fontFamily: "inherit",
    fontSize: 13,
    padding: "8px 10px",
    backgroundColor: "white",
    color: "#202b3b",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#dce1e9",
    borderRadius: 6,
    minWidth: 0,
  },
  search: { flex: 1, minWidth: 140 },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 7px",
    borderRadius: 4,
    fontSize: 11,
    backgroundColor: "#f0f2f6",
    color: "#5d6777",
    whiteSpace: "nowrap",
  },
  active: { backgroundColor: "#edf0ff", color: "#4a5cca" },
  done: { backgroundColor: "#edf6f1", color: "#33745c" },
  paused: { backgroundColor: "#fff6e6", color: "#9b6e21" },
  link: {
    color: { default: "#324eba", ":hover": "#172c7e" },
    textDecoration: "none",
  },
  item: {
    padding: "14px 20px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "#f0f2f6",
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: 500,
    marginBottom: 6,
    lineHeight: 1.5,
  },
  prose: {
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    lineHeight: 1.75,
    fontSize: 14,
    color: "#384457",
  },
  empty: {
    padding: "36px 22px",
    color: "#768092",
    fontSize: 13,
    lineHeight: 1.7,
  },
  error: {
    padding: "12px 16px",
    backgroundColor: "#fff1ed",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#f0c9be",
    borderRadius: 6,
    color: "#a9442e",
    marginBottom: 20,
    fontSize: 13,
  },
  section: { marginBottom: 24 },
  mono: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 11,
  },
  dialog: {
    width: "min(540px, 88vw)",
    maxHeight: "85vh",
    padding: 28,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#dce1e9",
    borderRadius: 12,
    boxShadow: "0 24px 90px #1b253730",
  },
  form: { display: "flex", flexDirection: "column", gap: 16 },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
    fontSize: 12,
    color: "#526075",
  },
  textArea: { minHeight: 150, resize: "vertical" },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "#7b8597",
    display: "inline-block",
  },
  liveDot: { backgroundColor: "#429775" },
});
