export type ColophonProps = {
  readonly recordCount: number;
  readonly generatedAt?: string;
};

/**
 * Footer line that names the generator and reaffirms the document is static.
 */
export function Colophon(props: ColophonProps) {
  return (
    <footer className="colophon" id="colophon">
      <p>
        Generated by <span className="mono">situ reports generate</span> from {props.recordCount}{" "}
        visible records. Static report, no runtime state
        {props.generatedAt !== undefined ? ` · generated ${props.generatedAt}` : ""}.
      </p>
    </footer>
  );
}
